### ISSUE TITLE
Puts the volume at 100%

### ISSUE THREAD

**Issue by Duxpower** [elibroftw/music-caster#27] opened 2021-07-18 18:50 UTC
Hey,

I like this program very much. 
Because it's the only alternative to VLC (which has no delay). 

This program however has delay, but the least amount compared to alternatives. 
However.. 

This program puts my soundbars volume at 100%, and no warnings or whatsoever when turning the program on. 
So if one has, say a youtube video, or music running. 
Chances are you will blow your speakers, so i'm just posting this to make other aware. 

Hopefully my new soundbar is not blown out now...

Great program non-theless. 
Only thing is, firewall has to be turned off for it to send audio  (program is allowed in FW) 

Thanks for your hard work!

**Comment by elibroftw** [comment] 2021-07-18 19:00
Do you mean that the first time Music Caster is used the volume is maxed? It is true so I did change it now. But after you set the volume through Music Caster, it should not reset to 100. I'm closing this just because I'm assuming you have not changed the volume through Music Caster and that the issue is with the default settings which I have no changed (Thanks).

**Closed by elibroftw** 2021-07-18 19:00 UTC
