### ISSUE TITLE
Server binded to wrong network adaptor

### ISSUE THREAD

**Issue by EricChan1989** [elibroftw/music-caster#76] opened 2024-09-25 13:17 UTC
Dear Developer,

I tried with the latest version of this software, and i failed to cast anything to my chromecast devices.
On the computer i use to install music caster, since I have docker desktop installed, it uses WSL, and have its related virtual network adapter in Hyper-V environment.
I tried to scan the QR code of the webui, and it always direct me to that virtual network adapter's IP instead of my physical one.
Also, I can detect the chromecast devices and casting to them, but after the initial successful handshaking (a sound to let us know it is connected), no any voice can be passed to the chromecast devices.
I use a windows 11 computer with cable network only ( i disabled the wireless network adaptor).
May i have your help on this?
I believe that it should always use my physical ethernet adapter for both casting and webui?

Thanks.

**Comment by elibroftw** [comment] 2024-09-25 13:53
I'll try to see. Are you able to access the webui from your mobile?

**Comment by EricChan1989** [comment] 2024-09-25 14:22
> I'll try to see. Are you able to access the webui from your mobile?

No, i cannot. Since it is a wsl virtual network adaptor, i can only access the webui from the computer i install this software. Mobile phone is in my local network which is nothing related to the wsl virtual network adaptor, so it doesn't work. Thanks

**Comment by elibroftw** [comment] 2024-09-25 14:57
Ah okay. This is then a bug related to the get up function. Can you provide the output of ipconfig?

**Comment by EricChan1989** [comment] 2024-09-25 23:25
yes, of course.
Please find the log file and the ipconfig as below.
You can see that it uses the 172.21.160.1 IP address, which is the Hyper-V WSL one.

2024-09-26 09:20:15,992 INFO (312) <module>(): Time to import is 0.81 seconds
2024-09-26 09:20:16,026 INFO (2662) background_thread(): system: Windows
2024-09-26 09:20:16,026 INFO (3956) start_on_login_modifications(): removing old startup shortcuts
2024-09-26 09:20:16,026 INFO (3958) start_on_login_modifications(): removed old startup shortcuts
2024-09-26 09:20:16,026 INFO (3959) start_on_login_modifications(): creating/removing startup registry entry
2024-09-26 09:20:16,026 INFO (3961) start_on_login_modifications(): created/removed startup registry entry
2024-09-26 09:20:16,325 INFO (4207) <module>(): LAN IPV4: 172.21.160.1:2001/
2024-09-26 09:20:16,329 INFO (4209) <module>(): LAN IPV6: [fe80::e911:84b9:1c8:cded]:2001/
2024-09-26 09:20:16,329 INFO (4260) <module>(): Time to start (excluding imports) is 0.31 seconds
2024-09-26 09:20:16,329 INFO (4261) <module>(): Time to start (including imports) is 1.12 seconds
2024-09-26 09:20:16,330 INFO (2897) activate_gui(): selected_tab=None

-------------------------------------------------------------------------
C:\Users\Administrator>ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : DESKTOP-QQDFQTI
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

Unknown adapter NordLynx:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : NordLynx Tunnel
   Physical Address. . . . . . . . . :
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::e911:84b9:1c8:cded%55(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.5.0.2(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . : 0.0.0.0
   DNS Servers . . . . . . . . . . . : 103.86.96.100
                                       103.86.99.100
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Realtek Gaming 2.5GbE Family Controller
   Physical Address. . . . . . . . . : [removed for security purpose]
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.2.2(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.2.1
   DNS Servers . . . . . . . . . . . : 1.1.1.1
                                       8.8.8.8
   NetBIOS over Tcpip. . . . . . . . : Enabled

Unknown adapter OpenVPN Data Channel Offload for NordVPN:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : OpenVPN Data Channel Offload
   Physical Address. . . . . . . . . :
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Unknown adapter Local Area Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : TAP-NordVPN Windows Adapter V9
   Physical Address. . . . . . . . . : [removed for security purpose]
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter WiFi:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) Wi-Fi 6 AX201 160MHz
   Physical Address. . . . . . . . . : [removed for security purpose]
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   Physical Address. . . . . . . . . : [removed for security purpose]
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 10:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   Physical Address. . . . . . . . . : [removed for security purpose]
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Bluetooth Device (Personal Area Network)
   Physical Address. . . . . . . . . : [removed for security purpose]
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : [removed for security purpose]
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::8593:9017:f01e:e94c%25(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.29.0.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 419435869
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-2E-2D-51-14-70-A6-CC-B2-9B-5C
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter vEthernet (WSL (Hyper-V firewall)):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #2
   Physical Address. . . . . . . . . : [removed for security purpose]
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::d5b0:1ea6:d494:c06f%50(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.21.160.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 838866269
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-2E-2D-51-14-70-A6-CC-B2-9B-5C
   NetBIOS over Tcpip. . . . . . . . : Enabled

Thank you very much for your prompt response!!

**Comment by elibroftw** [comment] 2024-09-30 01:19
Fixed in the latest version (5.20). Reopen if the issue is still present.

**Comment by EricChan1989** [comment] 2024-09-30 02:39
sorry, not yet fixed.
Just tested it, the same issue.
the server is still pointing to the same network adaptor, not working...

**Comment by elibroftw** [comment] 2024-09-30 03:45
This is when you scan it via your mobile? And you're on the latest version of music Caster?

**Comment by EricChan1989** [comment] 2024-09-30 05:09
yes, i am very sure that i downloaded the latest version of music caster, just hours ago.
when i scan the qr code, it is still binded to the 172 started IP instead of the 192 one, which is still the WSL one instead of my Lan IP. thanks

**Comment by elibroftw** [comment] 2024-10-02 00:05
It really shouldn't be returning 172 since I did parse the IP config output properly according to a test I added. There are some potential explanations, but I would need you to do some work. Can you run just normal `ipconfig` since that's what Music Caster calls?

If you have Python3 installed can you run the following code?

<details><summary>Code</summary>

```py
import re
from subprocess import DEVNULL, PIPE, CalledProcessError, Popen, check_output
import platform
import socket

IPV4_WIFI_PATTERN = re.compile(r'Wireless LAN adapter Wi-Fi:((.|\n)*?)?\s+IPv4 Address.*:\s*(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})')
IPV4_GENERAL_PATTERN = re.compile(r'IPv4 Address.*:\s*(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})')

def get_ipv4():
    try:
        if platform.system() != 'Windows':
            raise FileNotFoundError
        cmd_out = check_output(['ipconfig'], shell=True, text=True, encoding='iso8859-2')
        ipconfig_output = clean_ipconfig(cmd_out)
        assert cmd_out != ipconfig_output
        wifi_match = IPV4_WIFI_PATTERN.findall(ipconfig_output)
        if wifi_match:
            print(f'unexpected wifi match')
            return wifi_match[-1][-1]
        return IPV4_GENERAL_PATTERN.findall(ipconfig_output)[-1]
    except (IndexError, CalledProcessError, FileNotFoundError):
        print(f'unexpected exception {e}')
        assert False
        # fallback in case the ipv4 cannot be found in ipconfig
        # return next((i[4][0] for i in socket.getaddrinfo(socket.gethostname(), None) if i[0] == socket.AF_INET))
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            try:
                # doesn't even have to be reachable
                s.connect(('192.168.1.2', 1))
                ip = s.getsockname()[0]
            except Exception:
                ip = '127.0.0.1'
        return ip

def clean_ipconfig(ipconfig_raw):
    # TODO: there is a way to optimise this and return a single IP, but that requires matching each description
    ipconfig_output_split = ipconfig_raw.split('\n\n')[1:]
    filtered_output = ''
    for i in range(len(ipconfig_output_split) // 2):
        if 'WSL' not in ipconfig_output_split[i * 2] and 'Hyper-V' not in ipconfig_output_split[i * 2 + 1]:
            filtered_output += ipconfig_output_split[i * 2] + ipconfig_output_split[i * 2 + 1]
    return filtered_output

print(get_ip_v4())
```
</details>

**Comment by EricChan1989** [comment] 2024-10-02 03:50
yes, of course.
please find the attached files for both "normal ipconfig (without /all) and the screenshot of the result of running the python script.
You maybe wrote get_ip_v4 wrongly, and I changed it to get_ipv4 to make it work.
the original error message is also there in the screenshot.

from these 2 files, you can see that your python script picked up the 172.19.80.1 IP, which is the Ethernet adapter vEthernet.
it has a v there for virtual anyway.
My LAN ip is 192.168.2.2, at the 2nd top of the output list.
It seems that the last time it picked up the WSL one, and then this time it picks the other virtual one.
My other applications can always pick the physical cable network adaptor without issues.

Thanks again for your time and effort on this!

[ipconfig.txt](https://github.com/user-attachments/files/17219477/ipconfig.txt)
<img width="761" alt="screenshot" src="https://github.com/user-attachments/assets/486d21f7-c9df-4802-8489-76501157ae9d">

**Comment by elibroftw** [comment] 2024-10-04 02:54
Thank you. I wasn't sure whether to filter out vEthernet but it seems it also can be safely ruled out regarding local networking. Sorry for the 48hr delays, I'm trying to get in shape so I only have time for these things every other day and the weekend. 

v5.20.1 has the fix.

**Closed by elibroftw** 2024-10-04 02:54 UTC

**Comment by EricChan1989** [comment] 2024-10-04 03:20
thank you very much, and i will wait for the 5.20.1 version to be released.
your efforts are much appreciated!!
