### ISSUE TITLE
4.90.106 fails to run "DiscordNotFound"

### ISSUE THREAD

**Issue by onegrasshopper** [elibroftw/music-caster#32] opened 2021-11-15 07:36 UTC
Win10

4.90.102 install version works fine

4.90.105 Install version works fine. 
4.90.105 Portable version required .net core download, but does not show casting devices.

4.90.106 Music Caster keeps attempting to restart itself (3 instances in the task manager after starting). Same in install or portable version. Error in log has something to do with Discord? Is there an option to disable this feature /any connections to discord?

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 'EXCEPTION TYPE': 'DiscordNotFound',
 'FATAL': True,
 'LINE': 3087,
 'LOG': ['2021-11-14 23:30:02,427 INFO (2963): Function called: auto_update()'],
 'TRACEBACK': 'Traceback (most recent call last):\n'
              '  File "music_caster.py", line 3087, in <module>\n'
              '  File "pypresence/presence.py", line 13, in __init__\n'
              '  File "pypresence/baseclient.py", line 28, in __init__\n'
              'pypresence.exceptions.DiscordNotFound: Could not find Discord '
              'installed and running on this machine.\n',
 'VERSION': '4.90.106'

**Comment by elibroftw** [comment] 2021-11-15 12:32
I thought I had disabled the feature but I guess now. Just give me a couple hours.

**Comment by elibroftw** [comment] 2021-11-15 12:37
Wow they really made that library raise errors for no reason! Yeah it'll be fixed on a couple hours.

**Comment by elibroftw** [comment] 2021-11-15 13:33
Fixed. Sorry again for this bug, it wasn't caused by be directly.

**Closed by elibroftw** 2021-11-15 13:33 UTC
